export const productList = [
  {
    id: 1,
    name: "MacBook Pro 14",
    price: 2000,
    quantity: 50,
    brand: "Apple",
    desc: "Very fast laptop indeed!",
    status: "active",
  },
  {
    id: 2,
    name: "MacBook Pro 16",
    price: 3000,
    quantity: 30,
    brand: "Apple",
    desc: "Very fast laptop indeed!",
    status: "active",
  },
  {
    id: 3,
    name: "Huawei MateBook 13",
    price: 1200,
    quantity: 40,
    brand: "Huawei",
    desc: "Very fast laptop indeed!",
    status: "active",
  },
  {
    id: 4,
    name: "Lenovo IdeaPad",
    price: 1000,
    quantity: 150,
    brand: "Lenovo",
    desc: "Very fast laptop indeed!",
    status: "active",
  },
  {
    id: 5,
    name: "Microsoft Surface Book 3",
    price: 1500,
    quantity: 100,
    brand: "Microsoft",
    desc: "Very fast laptop indeed!",
    status: "active",
  },
];
